# Generated by Django 4.1.5 on 2023-01-04 07:28

from django.db import migrations, models
import django_countries.fields
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryInfo',
            fields=[
                ('id',
                 models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('country',
                 django_countries.fields.CountryField(max_length=2)),
                ('subdivision',
                 models.CharField(
                     blank=True, max_length=50, verbose_name='subdivision')),
            ],
            bases=(utils.models.ModelMixin, models.Model),
        ),
    ]
