# Generated by Django 4.1.5 on 2023-01-24 14:25

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True, primary_key=True, serialize=False,
                     verbose_name='ID')),
                ('name',
                 models.CharField(
                     max_length=50, unique=True, verbose_name='name')),
                ('frequency_type',
                 models.CharField(choices=[
                     ('mt', 'Weekly'), ('mt', 'Monthly'), ('yr', 'Yearly')
                 ], default='mt', max_length=2,
                     verbose_name='frequency type')),
                ('frequency',
                 models.IntegerField(
                     default=1, verbose_name='frequency')),
                ('amount',
                 models.DecimalField(
                     decimal_places=6, default=Decimal('0'), max_digits=19,
                     verbose_name='amount')),
                ('base_currency',
                 models.CharField(
                     default='EUR', max_length=3,
                     verbose_name='base currency')),
                ('description',
                 models.CharField(max_length=50, verbose_name='name')),
                ('is_active',
                 models.BooleanField(
                     default=False, help_text='Designates that this record '
                                              'is active.',
                     verbose_name='is active')),
            ],
            bases=(utils.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True, primary_key=True, serialize=False,
                     verbose_name='ID')),
                ('start_date',
                 models.DateTimeField(
                     auto_now_add=True, verbose_name='start date')),
                ('end_date',
                 models.DateTimeField(
                     default=datetime.datetime(
                         1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                     ), verbose_name='End date')),
                ('is_active',
                 models.BooleanField(
                     default=False, help_text='Designates that this record '
                                              'is active.',
                     verbose_name='is active')),
                ('subscription',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='subscription.subscription')),
                ('user',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to=settings.AUTH_USER_MODEL)),
            ],
            bases=(utils.models.ModelMixin, models.Model),
        ),
    ]
