# Generated by Django 4.1.5 on 2023-01-25 07:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(
                decimal_places=2, default=Decimal('0'), max_digits=19,
                verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='description',
            field=models.CharField(max_length=250,
                                   verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='frequency_type',
            field=models.CharField(choices=[
                ('wk', 'Weekly'), ('mt', 'Monthly'), ('yr', 'Yearly')
            ], default='mt', max_length=2, verbose_name='frequency type'),
        ),
    ]
