# Generated by Django 4.1.5 on 2023-01-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('subscription',
         '0003_subscriptionfeature_subscription_call_to_pick_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='is_active',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('no', 'None'), ('ex', 'Expired'),
                                            ('pp', 'Payment pending'),
                                            ('a', 'Active')], default='no',
                                   max_length=2, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='frequency_type',
            field=models.CharField(
                choices=[('mn', 'By the minute'), ('hr', 'Hourly'),
                         ('dy', 'Daily'), ('wk', 'Weekly'), ('mt', 'Monthly'),
                         ('yr', 'Yearly')], default='mt', max_length=2,
                verbose_name='frequency type'),
        ),
    ]
