# Generated by Django 4.1.5 on 2023-01-30 13:12

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):
    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True, primary_key=True,
                                     serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('base',
                 models.CharField(
                     max_length=3, verbose_name='base currency')),
                ('rates',
                 models.BinaryField(max_length=3000, verbose_name='rates')),
            ],
            bases=(utils.models.ModelMixin, models.Model),
        ),
    ]
