# Generated by Django 4.1.5 on 2023-01-13 10:31

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True, primary_key=True, serialize=False,
                     verbose_name='ID')),
                ('name',
                 models.CharField(
                     max_length=50, unique=True, verbose_name='name')),
            ],
            bases=(utils.models.ModelMixin, models.Model),
        ),
    ]
