# Generated by Django 4.1.5 on 2023-01-13 15:05

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True, primary_key=True, serialize=False,
                     verbose_name='ID')),
                ('type',
                 models.CharField(
                     choices=[
                         ('df', 'Dry/fluid'), ('w', 'Weight'), ('u', 'Unit')
                     ], default='df', max_length=2)),
                ('name',
                 models.CharField(
                     max_length=30, unique=True, verbose_name='name')),
                ('abbrev',
                 models.CharField(
                     max_length=20, verbose_name='abbreviation')),
                ('base_us',
                 models.DecimalField(decimal_places=5, max_digits=12)),
                ('base_metric',
                 models.DecimalField(decimal_places=5, max_digits=12)),
            ],
            bases=(utils.models.ModelMixin, models.Model),
        ),
    ]
