# Generated by Django 4.1.5 on 2023-01-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='measure',
            name='system',
            field=models.CharField(
                choices=[
                    ('us', 'US'), ('si', 'Metric'), ('1', 'Dimensionless')
                ], default='us', max_length=2),
        ),
        migrations.AlterField(
            model_name='measure',
            name='base_metric',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='measure',
            name='base_us',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
