# Generated by Django 4.1.5 on 2023-01-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_measure_is_default_measure_system_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='base_metric',
            field=models.DecimalField(decimal_places=10, default=1.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='measure',
            name='base_us',
            field=models.DecimalField(decimal_places=10, default=1.0, max_digits=19),
        ),
    ]
