# Generated by Django 4.1.5 on 2023-01-18 17:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_alter_measure_is_default_alter_measure_system_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True, primary_key=True, serialize=False,
                     verbose_name='ID')),
                ('text',
                 models.CharField(max_length=250, verbose_name='text')),
            ],
            bases=(utils.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True, primary_key=True, serialize=False,
                     verbose_name='ID')),
                ('name',
                 models.CharField(max_length=100, verbose_name='name')),
                ('food_id',
                 models.BigIntegerField(
                     default=0,
                     help_text='the id of the recipe from Food.com.')),
                ('prep_time',
                 models.DurationField(
                     default=datetime.timedelta(0),
                     verbose_name='preparation time')),
                ('cook_time',
                 models.DurationField(
                     default=datetime.timedelta(0),
                     verbose_name='cooking time')),
                ('date_published',
                 models.DateTimeField(
                     default=datetime.datetime(
                         1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc),
                     verbose_name='date published')),
                ('description',
                 models.CharField(
                     max_length=10000, verbose_name='description')),
                ('servings',
                 models.IntegerField(
                     default=0, verbose_name='number of servings')),
                ('recipe_yield',
                 models.CharField(
                     max_length=100, verbose_name='recipe yield')),
                ('calories',
                 models.FloatField(default=0, verbose_name='calories')),
                ('fat_content',
                 models.FloatField(default=0, verbose_name='fat content')),
                ('saturated_fat_content',
                 models.FloatField(
                     default=0, verbose_name='saturated fat content')),
                ('cholesterol_content',
                 models.FloatField(
                     default=0, verbose_name='cholesterol content')),
                ('sodium_content',
                 models.FloatField(default=0, verbose_name='sodium content')),
                ('carbohydrate_content',
                 models.FloatField(
                     default=0, verbose_name='carbohydrate content')),
                ('fibre_content',
                 models.FloatField(default=0, verbose_name='fibre content')),
                ('sugar_content',
                 models.FloatField(default=0, verbose_name='sugar content')),
                ('protein_content',
                 models.FloatField(
                     default=0, verbose_name='protein content')),
                ('author',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to=settings.AUTH_USER_MODEL)),
                ('category',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='recipes.category')),
            ],
            bases=(utils.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True, primary_key=True, serialize=False,
                     verbose_name='ID')),
                ('quantity',
                 models.CharField(max_length=30)),
                ('ingredient',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='recipes.ingredient')),
                ('recipe',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='recipes.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(
                through='recipes.RecipeIngredient', to='recipes.ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.ManyToManyField(to='recipes.instruction'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='keywords',
            field=models.ManyToManyField(to='recipes.keyword'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True, primary_key=True, serialize=False,
                     verbose_name='ID')),
                ('url',
                 models.CharField(max_length=250, verbose_name='image url')),
                ('recipe',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='recipes.recipe')),
            ],
            bases=(utils.models.ModelMixin, models.Model),
        ),
    ]
