# Generated by Django 4.1.5 on 2023-01-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_instruction_recipe_recipeingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='text',
            field=models.CharField(max_length=3000, verbose_name='text'),
        ),
    ]
