# Generated by Django 4.1.5 on 2023-01-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_instruction_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(max_length=1000, verbose_name='image url'),
        ),
    ]
