# Generated by Django 4.1.5 on 2023-02-08 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0009_alter_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='index',
            field=models.PositiveSmallIntegerField(default=1, validators=[
                django.core.validators.MinValueValidator(1),
                django.core.validators.MaxValueValidator(32767)
            ], verbose_name='index in ingredient list'),
        ),
    ]
