# Generated by Django 4.1.7 on 2023-03-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0012_recipeingredient_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True,
                                    upload_to='rns_images',
                                    verbose_name='image'),
        ),
    ]
