# Generated by Django 4.1.7 on 2023-03-10 11:25

from django.db import migrations

from user.permissions import (
    add_order_permissions_for_registered,
    remove_order_permissions_for_registered
)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_add_subs_permissions'),
    ]

    operations = [
        migrations.RunPython(
            add_order_permissions_for_registered,
            remove_order_permissions_for_registered),
    ]
