# Generated by Django 4.1.7 on 2023-03-14 08:16

from django.db import migrations

from user.permissions import (
    add_recipe_etc_permissions_for_registered,
    remove_recipe_etc_permissions_for_registered
)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_add_order_permissions'),
    ]

    operations = [
        migrations.RunPython(
            add_recipe_etc_permissions_for_registered,
            remove_recipe_etc_permissions_for_registered),
    ]
