# Generated by Django 4.1.5 on 2023-02-15 10:34

from random import uniform
from django.db import migrations

from recipesnstuff import RECIPES_APP_NAME
from recipesnstuff.settings import PRICING_FACTOR, DEFAULT_CURRENCY
from recipes.models import Recipe
from order.misc import generate_sku
from order.models import ProductType
from utils.database import table_exists


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    todo_operations = [
    ]

    if table_exists(f'{RECIPES_APP_NAME}_{Recipe.model_name()}'):
        # check recipe table exists (it won't in a migration on a
        # pristine database), before generating ingredient box skus
        todo_operations.extend([
            migrations.RunSQL(
                sql=[
                    ("INSERT INTO order_orderproduct "
                     "(type, sku, recipe_id, description, unit_price, "
                     "base_currency) VALUES (%s, %s, %s, %s, %s, %s);", [
                        ProductType.INGREDIENT_BOX.choice, sku, recipe_id,
                        f'Ingredient box for {name}',
                        round(uniform(3.0, 6.0), PRICING_FACTOR),
                        DEFAULT_CURRENCY.upper()
                     ])
                ],
                reverse_sql=[
                    ("DELETE FROM order_orderproduct WHERE "
                     "recipe_id=%s;", [recipe_id])
                ]
            ) for sku, recipe_id, name in [
                (generate_sku(ProductType.INGREDIENT_BOX, recipe=recipe),
                 recipe.id, recipe.name)
                for recipe in list(Recipe.objects.all())
            ]
        ])

    operations = todo_operations
