# Generated by Django 4.1.5 on 2023-03-02 16:36

from decimal import Decimal

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0002_generate_recipe_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='country',
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='type',
            field=models.CharField(
                choices=[('m', 'Miscellaneous'), ('s', 'Subscription'),
                         ('ib', 'Ingredient box'), ('cc', 'Cooking class'),
                         ('d0', 'Free delivery'),
                         ('d1', 'Standard delivery'),
                         ('d2', 'Premium delivery')],
                default='m', max_length=2,
                verbose_name='type'),
        ),
        migrations.AddField(
            model_name='order',
            name='amount_base',
            field=models.DecimalField(
                decimal_places=2, default=Decimal('0'), max_digits=19,
                verbose_name='amount (app base currency)'),
        ),
        migrations.AddField(
            model_name='order',
            name='was_1st_x_free',
            field=models.BooleanField(
                default=False, help_text='Designates this order was a first '
                                         'x free delivery.'),
        ),
    ]
