# Generated by Django 4.1.5 on 2023-03-03 08:16

from django.db import migrations

from checkout.models import Currency
from recipesnstuff import CHECKOUT_APP_NAME
from recipesnstuff.settings import DEFAULT_CURRENCY
from utils.database import table_exists

from order.views.maintenance import generate_random_price, delivery_options


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_add_orderproduct_country_and_more'),
    ]

    todo_operations = []

    if table_exists(f'{CHECKOUT_APP_NAME}_{Currency.model_name()}'):
        # check currency table exists (it won't in a migration on a
        # pristine database), before generating delivery skus
        todo_operations.extend([
            migrations.RunSQL(
                sql=[
                    ("INSERT INTO order_orderproduct "
                     "(type, sku, country, description, unit_price, "
                     "base_currency) VALUES (%s, %s, %s, %s, %s, %s);", [
                         opt.choice, sku, country, desc,
                         generate_random_price(pmin, pmax)
                         if pmin > 0 else 0,
                         DEFAULT_CURRENCY.upper()
                     ])
                ],
                reverse_sql=[
                    ("DELETE FROM order_orderproduct WHERE sku=%s;", [sku])
                ]
            ) for opt, sku, country, desc, pmin, pmax in delivery_options()
        ])

    operations = todo_operations
