# Generated by Django 4.1.7 on 2023-03-11 15:00

from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):
    """
    First of 4-step migration to change OrderProduct to Order through
    relationship
    Thanks to https://stackoverflow.com/a/51351406/4054609 for the steps
    """
    dependencies = [
        ('order', '0005_alter_order_order_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True, primary_key=True,
                                     serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(
                    default=0, verbose_name='quantity of product')),
                ('order',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='order.order')),
                ('order_prod',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='order.orderproduct')),
            ],
            bases=(utils.models.ModelMixin, models.Model),
        ),
    ]
