# Generated by Django 4.1.7 on 2023-03-11 15:02

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

from order.models import OrderItem as OrderItemModel
from recipesnstuff.constants import ORDER_APP_NAME


def create_through_relations(apps: StateApps,
                             schema_editor: BaseDatabaseSchemaEditor):
    """
    Create new through relationships to map OrderProduct to Order through
    OrderItem
    :param apps: apps registry
    :param schema_editor: editor generating statements to change database
                        schema
    """
    Order = apps.get_model(ORDER_APP_NAME, 'Order')
    OrderItem = apps.get_model(ORDER_APP_NAME, 'OrderItem')
    # copy order and order_prod info to new through model
    for order in Order.objects.all():
        for order_prod in order.items.all():
            OrderItem(**{
                f'{OrderItemModel.ORDER_FIELD}': order,
                f'{OrderItemModel.ORDER_PROD_FIELD}': order_prod,
                f'{OrderItemModel.QUANTITY_FIELD}': 0
            }).save()


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderitem'),
    ]

    operations = [
        migrations.RunPython(create_through_relations,
                             reverse_code=migrations.RunPython.noop),
    ]
