# Generated by Django 4.1.7 on 2023-03-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0008_remove_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='order.OrderItem',
                                         to='order.orderproduct'),
        ),
    ]
