# Generated by Django 4.1.7 on 2023-03-12 11:56

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0002_address'),
        ('order', '0009_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE,
                to='profiles.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'),
                                      max_digits=19,
                                      verbose_name='subtotal amount'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='base_currency',
            field=models.CharField(default='EUR', max_length=3,
                                   verbose_name='currency'),
        ),
    ]
